config/routes.rb
Rails.application.routes.draw do
  root 'readies#landing'
  resource :readies, except: %i[edit update destroy] do
    collection do
      get :readme
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/readie.rb
class Readie < ApplicationRecord
  validates :token, presence: true, uniqueness: true

  before_validation :generate_token

  has_many :readie_reads, dependent: :destroy

  def read
    ReadieRead.create!(readie: self)
  end

  private

  def generate_token
    begin
      self.token = SecureRandom.urlsafe_base64(nil, false)
    end while Readie.exists?(token: token)
  end
end

app/models/readie_read.rb
class ReadieRead < ApplicationRecord
  belongs_to :readie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/readies_controller.rb
class ReadiesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  before_action :set_readie, only: %i[show readme]

  # GET /readies
  # GET /readies.json
  def landing() end

  # GET /readies/1
  # GET /readies/1.json
  def show() end

  # GET /readies/new
  def new() end

  # POST /readies
  # POST /readies.json
  def create
    @readie = Readie.new

    respond_to do |format|
      if @readie.save
        format.json { render @readie, status: :created }
      else
        format.json { render json: @readie.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def readme
    if request.format.html?
      render :nice_try, status: :ok
    elsif request.format.json?
      @readie.read
      send_data(ActionController::Base.helpers.asset_path('img.png'), type: 'image/png')
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_readie
    token = params[:token]
    if token.blank?
      render :nice_try, status: :ok
      return
    end
    @readie = Readie.find_by(token: token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readies_helper.rb
module ReadiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/readies/landing.html.erb
<div class="split left not-selectable">
  <%= link_to new_readies_url do %>
    <div class="centered zoom">
      <h2>Create a Readie</h2>
      <p>Generate a new Readie for a new email</p>
    </div>
  <% end %>
</div>

<div class="split right not-selectable">
  <a data-toggle="modal" data-target="#readie_token_modal">
    <div class="centered zoom">
      <h2>Check a Readie</h2>
      <p>Check whether an existing Readie got read yet</p>
    </div>
  </a>
</div>

<!-- Modal -->
<div id="readie_token_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <%= form_tag("/readies", method: :get) do %>
    <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Token</h4>
        </div>
        <div class="modal-body">
          <p>Enter the Readie token you were asked to store when you created the Readie:</p>

            <div class="form-group">
              <input class="form-control" id="token" placeholder="Enter token" name="token">
            </div>
        </div>
        <div class="modal-footer">
           <%= submit_tag("Find my Readie Reads!", class: "btn btn-warning white" ) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/readies/new.html.erb
<div class="row not-selectable no-cursor">
	<div class="col-md-12 col-sm-12">
		<div class="question-box">
			<div class="row">
				<div class="col-md-2 col-sm-2">
					<%= link_to('Back', root_url, class: 'btn-back btn btn-block btn-outline-info') %>
				</div>
				<div class="col-md-4 col-sm-4 offset-md-2 offset-sm-2">
					<h2 class="title">Generate a Readie</h2>
				</div>
			</div>
			<div class="progress-bar-div separator-div" style="border-top: 2px solid #f3f3f3;">
				<div class="progress">
					<div id="progress_bar" class="progress-bar progress-bar-striped bg-info" role="progressbar" aria-valuenow="10"
					aria-valuemin="0" aria-valuemax="100" style="width:25%">
					25%
				</div>
			</div>
		</div>
			<div class="question-area">
				<div class="learn">

					<div class="separator-div row margin-up padding-down">
					<div class="col-md-12 col-sm-12 center">
							<h3>What is a Readie?</h3>
							<p>A Readie is a slick trick you can use to know whether somebody opened the email you sent them or not.</p>
							<p>Readie works using a very common trick. The code you will be using will insert an invisible image (0x0 pixels) into your email. Once the recepient opens the email, the image will be displayed and we will know that the email was opened!</p>
						</div>
					</div>
				</div>
				<div class="center" style="margin-top: 8px;">
						<button onclick="loadSecondDiv()" id="cont" class="btn btn-info btn-lg" style="font-size: 16px;">Next</button>
					</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div id="confirmModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirmation</h4>
      </div>
      <div class="modal-body">
        <p>Please confirm creating your Readie.</p>
      </div>
      <div class="modal-footer">
        <button onclick="createReadie()" type="button" class="btn btn-info" data-dismiss="modal">Confirm</button>
      </div>
    </div>

  </div>
</div>
<script>

function loadSecondDiv() {
  $("#cont").remove();
  $("#progress_bar").html("50%");
  $("#progress_bar").css("width", "50%");
  $(".learn").append("<div id='second_div' class='row margin-up padding-down separator-div'><div class='col-md-12 col-sm-12 center'><h3>How to use it?</h3><p>Upon generating a Readie, you will see 2 boxes with some sort of code inside each of them. One is used to add the Readie to your email, and the other is used to check the status of your Readie. More instructions will follow after you generate your Readie.</p></div></div>");
  $("#second_div").hide().show("slow");
  $(".learn").after('<div class="center" style="margin-top: 8px;"><button data-toggle="modal" data-target="#confirmModal" id="cont" class="btn btn-info btn-lg" style="font-size: 16px;">Generate</button></div>');
  scroll("#second_div");
}

function createReadie(url) {
  $.post("/readies.json/")
    .done(function(data){
			console.log(data);
      loadThirdDiv(data);
      loadTooltips();
    });
}

function loadTooltips() {
  $('[data-toggle="tooltip"]').tooltip();
  $('pre.copiable').click(function() {
    copy(this.children[0]);
		$(this).attr('data-original-title', 'Copied!').tooltip('show');
  });
	$('pre.copiable').mouseleave(function() {
	  $(this).attr('data-original-title', 'Click to copy').tooltip();
	});
}

function loadThirdDiv(readie) {
	var url = readie.url.split('.json')[0] + '/readme.json'
  $("#cont").remove();
  $("#progress_bar").html("75%");
  $("#progress_bar").css("width", "75%");
  $(".learn").append('<div id="third_div" class="row margin-up padding-down separator-div"> <div class="col-md-6 col-sm-6 center"> <h3>Use This</h3> <pre class="copiable" data-toggle="tooltip" title="Click to Copy!" data-placement="bottom"> <code> &lt;img src="' + url + '?token=' + readie.token + '" width="0" height="0"/></code> </pre> </div> <div class="col-md-6 col-sm-6 center"> <h3>Store This</h3> <pre class="copiable" data-toggle="tooltip" title="Click to Copy!" data-placement="bottom"> <code>' + readie.token + '</code> </pre> </div> </div>');
  $("#third_div").hide().show("slow");
  $(".learn").after('<div class="center" style="margin-top: 8px;"><button onclick="loadFourthDiv()" id="cont" class="btn btn-info btn-lg" style="font-size: 16px;">Next</button></div>');
  scroll("#third_div");
}

function loadFourthDiv() {
  $("#cont").remove();
  $("#progress_bar").html("100%");
  $("#progress_bar").css("width", "100%");
  $(".learn").append("<div id='fourth_div' class='row margin-up padding-down separator-div'><div class='col-md-12 col-sm-12 center'><h3>Use it</h3><p><ul style='text-align: left;'><li>Go on about writing your email as usual. When you finish writing it, type '****' into your email body on a new line.</li><li>Right click the stars and click Inspect (or Inspect Element on Safari - You may need to enable 'Show develop menu in menu bar' from Preferences > Advanced). </li><li>Right click the stars and choose Edit as HTML.</li><li>Highlight the stars and paste the code you copied to replace them then press CTRL(CMD) + Enter to apply.</li><li>Make sure you do not backspace the end of your email or select-all and delete your text as that might remove the code you added.</li><li>That is it! Send your email and come back later to check if it has been read!</li><br><p>Please note that Readie has no way of knowing who opened the email. This means that if you open the email yourself (in your sent folder for example), Readie will show that on the website.</p></ul></p></div></div>");
  $("#fourth_div").hide().show("slow");
  scroll("#fourth_div");
}

function scroll(id) {
  var tag = $(id);
    $('html, body').animate({
        scrollTop: tag.offset().top - 100
    }, 'slow');
}

function copy(that){
    // console.log(that);
    var inp = document.createElement('input');
    document.body.appendChild(inp)
    inp.value = that.textContent
    inp.select();
    document.execCommand('copy',false);
    inp.remove();
  }

$(function() {
	$("body").css("background-color", "#094452");
});

</script>

app/views/readies/nice_try.html.erb
<h1 id="nice_try" class="not-selectable centered">Nice try!</h1>

<script>
  $(function() {
  	$("body").css("background-color", "#e28332");
  });
</script>

app/views/readies/show.html.erb
<div class="centered no-cursor">
  <h1>Readie Read?</h1>
  <br />
  <br />
  <% if !@readie || @readie.readie_reads.size < 3 %>
  <h3>This Readie has not been read yet, check again later!</h3>
  <% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Number</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @readie.readie_reads.each_with_index do |r_r, i| %>
        <% next if i < 2 %>
        <tr>
          <td><%= i - 1 %></td>
          <td><%= r_r.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br />
  <p>
    Total number of reads is: <%= @readie.readie_reads.size - 2 %>
  </p>
  <% end %>
  <br />
  <%= link_to('Back', root_url, class: 'btn-back btn btn-lg back-show') %>
</div>

<script>
  $(function() {
  	$("body").css("background-color", "#e28332");
  });
</script>